### ISSUE TITLE
infoAdicional does not appear on bank statement

### ISSUE THREAD

**Issue by Iazzetta** [thalesog/pix-utils#16]
- **I'm submitting a ...**
  [ X ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

I'm having trouble generating a pix key (brcode) with additional information (message).
I have another project that gets the message sent on the PIX to relate to my bank.
When I do a pix manually, sending a message, my script finds the message.
But when I use pix-utils passing an `infoAdditional`, when sending the PIX the message appears,
but when I see the extract there is no message.

Would it be something outdated in the lib, a bug or is the function to add a message not implemented?
`infoAdditional` is the custom message right?

Thanks

**Comment by thalesog** [comment]
Can you provide an exemple where this bug happens?

**Comment by Iazzetta** [comment]
I'm using [pynubank](https://github.com/andreroggeri/pynubank) to access my account and read custom messages to validate pix.

I create a pix brcode with generated code to validate:

```
const verify_code = `Order ${makeid(6)}`
const pix = createStaticPix({
          merchantName: 'Company',
          merchantCity: 'City',
          pixKey: 'xxxxx',
          infoAdicional: verify_code,
          transactionAmount: 0.01,
          isTransactionUnique: true
}).throwIfError();
const brCode = pix.toBRCode();
```

The pix is generated and works fine. But When I check the messages from pix in my nubank account I can't find the message body (I guess is the infoAdicional option). But when I do a manually pix and set custom message works fine. I don't know what is the problem.

**Comment by thalesog** [comment]
That's the expected behavior. 
The `infoAdicional` field its like an "question" to the payer, so he has to manually fill the "Description" field to you receive in your extract.

**Comment by thalesog** [comment]
Closing this issue as solved. Please feel free to reopen if you have any further questions.
