### ISSUE TITLE
Pix Dinamico

### ISSUE THREAD

**Issue by cesarhfborges** [thalesog/pix-utils#24]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [*] question about how to use this project

- Como funciona o PIX dinâmico?

Baseado neste exemplo:
const pix = createDynamicPix({
  merchantName: 'Thales Ogliari',
  merchantCity: 'Sao Paulo',
  url: 'https://pix.thalesogliari.com.br',
}).throwIfError();

Percebi que passamos apenas 3 parametros,
mas minha duvida é, para que serve a URL?
o que acontece com ela ? após o pagamento ela vai ser chamada pelo banco ao concluir a transação ?
e se ele é dinâmico por que não tem o campo valor ?

**Comment by Joao-1** [comment]
Creio que a URL neste caso é a URL definida no [Manual de Padrões para Iniciantes do Pix](https://www.bcb.gov.br/content/estabilidadefinanceira/pix/Regulamento_Pix/II_ManualdePadroesparaIniciacaodoPix.pdf), na seção que definine o QrCode dinâmico. 

Serve para mandar informações de quem tá lendo o QrCode.
